# Personal Finance Data Cleaning
## importing libraries

In [22]:
import pandas as pd
import numpy as np

## Load Dataset

In [23]:

df = pd.read_csv("Expenses_clean.csv")
df = df.copy()

## exploring the data

In [24]:
df.head()

             date_time          category account  amount currency   tags
0  2025-11-30 00:00:00            Health  acct_1   114.0      BYN  tag_1
1  2025-11-29 00:00:00              Food  acct_1     5.0      BYN  tag_1
2  2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
3  2025-11-27 00:00:00              Cafe  acct_1    10.0      BYN  tag_1
4  2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1

In [25]:
df.tail()

               date_time          category account  amount currency   tags
933  2025-01-10 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
934  2025-01-10 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
935  2025-01-09 00:00:00              Taxi  acct_1    14.0      BYN  tag_1
936  2025-01-08 00:00:00              Taxi  acct_1    15.0      BYN  tag_1
937  2025-01-07 00:00:00              Food  acct_1     5.0      BYN  tag_1

In [26]:
df.shape
df.dtypes

date_time     object
category      object
account       object
amount       float64
currency      object
tags          object
dtype: object

In [27]:
df.info

<bound method DataFrame.info of                date_time          category account  amount currency   tags
0    2025-11-30 00:00:00            Health  acct_1   114.0      BYN  tag_1
1    2025-11-29 00:00:00              Food  acct_1     5.0      BYN  tag_1
2    2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
3    2025-11-27 00:00:00              Cafe  acct_1    10.0      BYN  tag_1
4    2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
..                   ...               ...     ...     ...      ...    ...
933  2025-01-10 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
934  2025-01-10 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
935  2025-01-09 00:00:00              Taxi  acct_1    14.0      BYN  tag_1
936  2025-01-08 00:00:00              Taxi  acct_1    15.0      BYN  tag_1
937  2025-01-07 00:00:00              Food  acct_1     5.0      BYN  tag_1

[938 rows x 6 columns]>

In [28]:
df.describe()

            amount
count   938.000000
mean     15.842217
std      78.291145
min       0.000000
25%       1.000000
50%       2.000000
75%      10.000000
max    1172.000000

In [29]:
df.isnull().sum()

date_time    0
category     0
account      0
amount       0
currency     0
tags         0
dtype: int64

## hhandling the duplicates

In [30]:
df.duplicated().sum()

np.int64(145)

In [31]:
df.drop_duplicates(inplace=True)

## removing unnecessary columns

In [32]:
# Removing the 'currency' column because it contains only one unique value (BYN)
# and does not contribute to the analysis.
df.drop(columns=['currency'], inplace=True)

## Convert Data Types

In [33]:
df["date_time"]=pd.to_datetime(df["date_time"])

## feature engineering

In [34]:
df["Month"] = df["date_time"].dt.month_name()

In [35]:
df["Day_of_Week"] = df["date_time"].dt.day_name()

In [36]:
df["Is_Weekend"] = df["date_time"].dt.dayofweek >= 5

In [37]:
df[df["amount"] < 0]

Empty DataFrame
Columns: [date_time, category, account, amount, tags, Month, Day_of_Week, Is_Weekend]
Index: []

In [38]:
df["category"].unique()

array(['Health', 'Food', 'Public transport', 'Cafe', 'Taxi', 'Gifts',
       'Loan given', 'Leisure', 'Clothes', 'Bought for myself', 'Other',
       'University', 'Job', 'Fines'], dtype=object)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 793 entries, 0 to 937
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date_time    793 non-null    datetime64[ns]
 1   category     793 non-null    object
 2   account      793 non-null    object
 3   amount       793 non-null    float64
 4   tags         793 non-null    object
 5   Month        793 non-null    object
 6   Day_of_Week  793 non-null    object
 7   Is_Weekend   793 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(1), object(5)
memory usage: 50.3+ KB

## Export Cleaned Dataset

In [42]:
df.to_csv("Expenses_Final.csv", index=False)
df.head()

,date_time,category,account,amount,tags,Month,Day_of_Week,Is_Weekend
0,2025-11-30,Health,acct_1,114.0,tag_1,November,Sunday,True
1,2025-11-29,Food,acct_1,5.0,tag_1,November,Saturday,True
2,2025-11-27,Public transport,acct_2,1.0,tag_1,November,Thursday,False
3,2025-11-27,Cafe,acct_1,10.0,tag_1,November,Thursday,False
5,2025-11-26,Cafe,acct_3,2.0,tag_1,November,Wednesday,False